[build]
  # Comando de build personalizado para configurar variables de entorno
  command = "node build.js"
  publish = "."

[build.environment]
  # Variables de entorno que se usarán en el build
  # IMPORTANTE: Configura REMOVE_BG_API_KEY en el dashboard de Netlify
  # Ve a Site settings > Environment variables y agrega:
  # REMOVE_BG_API_KEY = tu_api_key_real_aqui
  REMOVE_BG_API_KEY = ""

# Configuración de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración de redirects para SPA
# IMPORTANTE: Excluir funciones de Netlify del redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Excluir rutas que no deben ser redirigidas
  except = ["/.netlify/*", "/api/*", "/*.js", "/*.css", "/*.png", "/*.jpg", "/*.jpeg", "/*.gif", "/*.svg", "/*.ico", "/*.woff", "/*.woff2", "/*.ttf", "/*.eot"]
