[build]
  # Sin comando de build personalizado - Netlify usará configuración por defecto
  publish = "."
  
# Configuración de Node.js para Netlify
[build.environment]
  NODE_VERSION = "18"

# Configuración de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración de redirects para SPA
# IMPORTANTE: Excluir funciones de Netlify del redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Excluir rutas que no deben ser redirigidas
  except = ["/.netlify/*", "/api/*", "/*.js", "/*.css", "/*.png", "/*.jpg", "/*.jpeg", "/*.gif", "/*.svg", "/*.ico", "/*.woff", "/*.woff2", "/*.ttf", "/*.eot"]
